package com.amazonaws.mobilehelper.auth.signin.ui;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.BitmapDrawable;
import android.support.annotation.Nullable;
import android.util.AttributeSet;
import android.util.Log;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;

import com.amazonaws.mobilehelper.R;
import com.amazonaws.mobilehelper.auth.signin.SignInManager;
import com.amazonaws.mobilehelper.auth.signin.ui.userpools.UserPoolSignInView;
import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;

import static com.amazonaws.mobilehelper.auth.signin.ui.DisplayUtils.dp;

/**
 * View for displaying sign-in components.
 */
public class SignInView extends LinearLayout {
    private static final String LOG_TAG = SignInView.class.getSimpleName();
    private static final int MAX_IMAGE_HEIGHT = dp(250);
    private static final int IMAGE_MARGINS = dp(20);

    private ImageView imageView;
    private UserPoolSignInView userPoolSignInView;
    private SplitBackgroundDrawable splitBackgroundDrawable;
    private final int signInButtonMargin;

    public SignInView(Context context) {
        this(context, null);
    }

    public SignInView(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public SignInView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

        this.setOrientation(VERTICAL);
        this.setGravity(Gravity.CENTER_HORIZONTAL);
        final int logoResId;
        final int backgroundColor;
        if (isInEditMode()) {
            backgroundColor = Color.DKGRAY;
            logoResId = R.mipmap.default_sign_in_logo;
        } else {
            final AWSMobileHelperConfiguration helperConfig = SignInManager.getInstance()
                .getIdentityManager().getHelperConfiguration();
            backgroundColor = helperConfig.getSignInBackgroundColor(Color.DKGRAY);
            logoResId = helperConfig.getSignImageResourceId(R.mipmap.default_sign_in_logo);
        }
        splitBackgroundDrawable = new SplitBackgroundDrawable(0, backgroundColor);
        setBackgroundDrawable(splitBackgroundDrawable);

        imageView = new ImageView(context);
        final Bitmap bitmap = BitmapFactory.decodeResource(getResources(), logoResId);
        final BitmapDrawable bitmapDrawable = new BitmapDrawable(getResources(), bitmap);
        imageView.setImageDrawable(bitmapDrawable);
        imageView.setScaleType(ImageView.ScaleType.FIT_XY);
        imageView.setAdjustViewBounds(true);

        final LinearLayout.LayoutParams imageLayoutParams
            = new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
        imageLayoutParams.setMargins(dp(10), 0, dp(10), 0);
        addView(imageView, imageLayoutParams);

        userPoolSignInView = new UserPoolSignInView(context);
        final LinearLayout.LayoutParams userPoolLayoutParams
            = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        addView(userPoolSignInView, userPoolLayoutParams);
        signInButtonMargin = getResources().getDimensionPixelSize(R.dimen.sign_in_button_margin);

    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        resizeImageView();
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }

    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        super.onLayout(changed, l, t, r, b);
        if (userPoolSignInView.getVisibility() == VISIBLE) {
            final int splitPoint =
                userPoolSignInView.getTop() +
                    (userPoolSignInView.getCredentialsFormView().getMeasuredHeight() / 2);
            splitBackgroundDrawable.setSplitPointDistanceFromTop(splitPoint);
        }
    }

    private void resizeImageView() {
        int availableHeight = getMeasuredHeight();

        availableHeight -= userPoolSignInView.getMeasuredHeight();

        // Subtract the top and bottom image margins
        availableHeight -= (2 * IMAGE_MARGINS);

        // Leave a space at least equal to the size of the sign-in button margin on the bottom of the view.
        availableHeight -= signInButtonMargin;

        if (availableHeight > MAX_IMAGE_HEIGHT) {
            availableHeight = MAX_IMAGE_HEIGHT;
        }

        imageView.getLayoutParams().height = availableHeight;
        imageView.getLayoutParams().width = availableHeight;

        ((LayoutParams)imageView.getLayoutParams()).setMargins(
            IMAGE_MARGINS, IMAGE_MARGINS, IMAGE_MARGINS, IMAGE_MARGINS);
        imageView.setLayoutParams(imageView.getLayoutParams());
        Log.d(LOG_TAG, "imageViewHeight: " + availableHeight);
    }
}
