package com.mysampleapp.demo;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import android.content.Context;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import com.amazonaws.mobile.api.CloudLogicAPIFactory;
import com.amazonaws.mobile.api.CloudLogicAPIConfiguration;
import com.mysampleapp.MainActivity;
import com.mysampleapp.R;

/**
 * Selects one of the Amazon API Gateway REST APIs to demonstrate.
 */
public class CloudLogicAPIChooserFragment extends DemoFragmentBase
    implements AdapterView.OnItemClickListener {

    /** Log tag. */
    private static final String LOG_TAG = CloudLogicAPIChooserFragment.class.getSimpleName();

    private static final CloudLogicAPIConfiguration[] API_CONFIGURATIONS = CloudLogicAPIFactory.getAPIs();

    private ListView listView;

    @Override
    public View onCreateView(final LayoutInflater inflater, final ViewGroup container,
                             final Bundle savedInstanceState) {

        // Inflate the layout for this fragment
        final View fragmentView = inflater.inflate(R.layout.fragment_demo_cloudlogic_api_chooser, container, false);

        final ArrayAdapter adapter =
                new ArrayAdapter<CloudLogicAPIConfiguration>(getContext(), R.layout.list_item_cloudlogic_api_chooser, API_CONFIGURATIONS) {
            @Override
            public View getView(final int position, final View convertView, final ViewGroup parent) {

                final View view;

                if (convertView == null) {
                    final LayoutInflater inflater = (LayoutInflater) getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
                    view = inflater.inflate(R.layout.list_item_cloudlogic_api_chooser, parent, false);
                } else {
                    view = convertView;
                }

                final TextView title = (TextView)view.findViewById(R.id.list_item_cloudlogic_api_chooser_title);
                final TextView description = (TextView)view.findViewById(R.id.list_item_cloudlogic_api_chooser_description);
                final TextView endpoint = (TextView)view.findViewById(R.id.list_item_cloudlogic_api_chooser_endpoint);
                final CloudLogicAPIConfiguration itemConfiguration = API_CONFIGURATIONS[position];

                title.setText(itemConfiguration.getDisplayName());
                description.setText(itemConfiguration.getDescription());
                endpoint.setText(itemConfiguration.getEndpoint());
                return view;
            };
        };

        listView = (ListView)fragmentView.findViewById(R.id.cloudlogic_api_chooser_list);
        listView.setAdapter(adapter);
        listView.setOnItemClickListener(this);

        return fragmentView;
    }

    @Override
    public void onItemClick(final AdapterView<?> parent, final View view, final int position, final long id) {
        Log.d(LOG_TAG, "onItemClick: " + position);

        final CloudLogicAPIConfiguration configuration =
                (CloudLogicAPIConfiguration)parent.getAdapter().getItem(position);
        final String apiName = configuration.getDisplayName();
        final Bundle bundle = new Bundle();
        bundle.putInt(CloudLogicMethodChooserFragment.BUNDLE_ARG_API_INDEX, position);

        final Fragment fragment = CloudLogicMethodChooserFragment.newInstance();
        fragment.setArguments(bundle);

        getFragmentManager()
                .beginTransaction()
                .addToBackStack(null)
                .replace(R.id.main_fragment_container, fragment, apiName)
                .commit();
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);

        // Clear fragment bundle
        ((MainActivity)getActivity()).setFragmentBundle(null);
    }
}
