package com.amazonaws.mobilehelper.auth.signin.ui.userpools;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import static com.amazonaws.mobilehelper.auth.signin.ui.DisplayUtils.dp;

/**
 * Common constants for user pool forms.
 */
public final class UserPoolFormConstants {
    /** Form Button Color. */
    public static final int FORM_BUTTON_COLOR = 0xff4599ff;

    /** Form button radius in pixels. */
    public  static final int FORM_BUTTON_CORNER_RADIUS = dp(5);

    /** Ratio for the form size relative to the parent view. */
    public static final double FORM_SIDE_MARGIN_RATIO = 0.85;

    /** Maximum width of the form in pixels. */
    public static final int MAX_FORM_WIDTH_IN_PIXELS = dp(300);
}
