package com.amazonaws.mobilehelper.auth.signin;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool;
import com.amazonaws.mobilehelper.auth.IdentityProvider;
import com.amazonaws.mobilehelper.auth.user.AbstractIdentityProfile;
import com.amazonaws.mobilehelper.auth.user.IdentityProfile;
import com.amazonaws.mobilehelper.auth.user.ProfileRetrievalException;

import java.util.Collections;
import java.util.Map;

/**
 * Identity Profile for User Pools.
 */
public class CognitoUserPoolsIdentityProfile extends AbstractIdentityProfile {
    /** Log tag. */
    private static final String LOG_TAG = CognitoUserPoolsIdentityProfile.class.getSimpleName();

    /** User's name. */
    private String userName;

    @Override
    public String getUserImageUrl() {
        return null;
    }

    @Override
    public String getUserName() {
        return userName;
    }

    @Override
    public Map<String, String> getCustomProfileAttributesMap() {
        return Collections.emptyMap();
    }

    @Override
    public IdentityProfile loadProfileInfo(IdentityProvider provider) throws ProfileRetrievalException {
        if (!provider.refreshUserSignInState()) {
            throw new ProfileRetrievalException(
                "Can't load user info, due to no longer signed in with " + provider.getDisplayName());
        }
        final CognitoUserPoolsSignInProvider cognitoUserPoolsSignInProvider =
            (CognitoUserPoolsSignInProvider) provider;
        final CognitoUserPool cognitoUserPool =
            cognitoUserPoolsSignInProvider.getCognitoUserPool();

        if (null != cognitoUserPool && null != cognitoUserPool.getCurrentUser()) {
            userName = cognitoUserPool.getCurrentUser().getUserId();
        }
        return this;
    }
}
