//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//
package com.amazonaws.mobile;

import android.graphics.Color;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;
import com.mysampleapp.R;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 05e0cdda-2625-4fd6-906c-afc4a8132c91 aws-my-sample-app-android-v0.18";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-west-2");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-west-2:791da0ce-1ecc-4c1d-a427-eafa0d6c4d6f";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "joyfulchurch-userfiles-mobilehub-687604833";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-west-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-west-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-west-2_SDOpd56WN";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "4uvof73eivpevcsbdr4avbscn6";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1k2pfq9ce8dmpj3pf1b70fqih810dbtq9aqncc36absq0gps9k42";

    private static final AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .withCognitoUserPool(AMAZON_COGNITO_USER_POOL_ID,
            AMAZON_COGNITO_USER_POOL_CLIENT_ID, AMAZON_COGNITO_USER_POOL_CLIENT_SECRET)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}
